### ISSUE TITLE
Current power consumption not updated

### ISSUE THREAD

**Issue by lucasvdh** [koktaildotcom/com.p1.smartmeter-dsmr.reader#1]
The current power consumption is not updated in the new homey device. The value does update when I run the old p1 reader script.

Haven't done any debugging yet, just noticed this issue. Keeping the old reader running till the issue is fixed. Soonest I'll have some time to debug will prob be next week.

**Comment by koktaildotcom** [comment]
That is not suppose to happen. I don't have the old driver anymore because I've factory reset my development homey unfortunately. Can see in the new driver what data you are missing?

**Comment by koktaildotcom** [comment]
I've moved the issue to the https://github.com/koktaildotcom/com.p1.smartmeter repository, because the json is the same as the previous implementation

**Comment by pro-sumer** [comment]
@koktaildotcom I think this actually is a bug in this new script:

Shouldn't `output.power.totalConsumed` on line 62 be `output.power.actualConsumed`?

(looks like a copy/paste error...)

**Comment by koktaildotcom** [comment]
@pro-sumer good spot! I've updated the value and that will fix this issue. Many thanks for your suggestion.

**Comment by lucasvdh** [comment]
Thanks :smile:
