### ISSUE TITLE
package-lock.json results in incorrect power usage

### ISSUE THREAD

**Issue by rkokkelk** [koktaildotcom/com.p1.smartmeter-dsmr.reader#17]
When using your apps, I've noticed that my power usage in the Homey app was inverted. Delving into the issue, which I first mentioned [here](https://github.com/koktaildotcom/com.p1.smartmeter/issues/41), I've noticed that it was due to a bug in the used `node-dsmr` module. This bug, however, has been fixed for a long time see my relevant issue [here](https://github.com/reneklootwijk/node-dsmr/issues/19)

However, due to the `package-lock.json` file being present in this repo, `npm` uses the older package versions instead of the current available versions. This results both in package versions containing security vulnerabilities, as mentioned by npm, but also uses the bug version of `node-dsmr`. Removing `package-lock.json` and removing `node-modules` and performing `npm install` fixed all my issues.

This issue is partially related to: #14

**Comment by koktaildotcom** [comment]
Thanks for investigating this issue. I've updated the dependencies
