### ISSUE TITLE
Problem in p1.js (with bits)

### ISSUE THREAD

**Issue by Itsmmai** [koktaildotcom/com.p1.smartmeter-dsmr.reader#19]
Hi,

https://github.com/reneklootwijk found out that there is a problem in your p1.js. when bits are important this script is not working. I need to use:

const usbPort = '/dev/ttyUSB0'
const bps = 9600
const bits = 7
const parity = 'none'

then 

const p1Meter = new dsmr({
    port: usbPort,
    baudrate: bps,
    databits: bits,       <---= changed !!
    parity: parity

now almost everything is working. Only the current usage is still not working for me.

Bye,
Abel

**Comment by koktaildotcom** [comment]
I have updated the changes. Thanks for reporting this bug!
