### ISSUE TITLE
Produced energy is added positively with DMSR-reader plugin. 

### ISSUE THREAD

**Issue by Ruben9477** [koktaildotcom/com.p1.smartmeter-dsmr.reader#20]
Hi, 

Since I am using the DSMR-reader plugin instead of the stand-alone application, produced energy is added positively. 
Resulting a wrong total energy in Homey. 

Anyone has an idea how to fix this? 

Thanks! 
![Schermafbeelding 2021-11-29 om 20 51 53](https://user-images.githubusercontent.com/90531431/143933950-da2295a3-03d4-40e2-ad2a-2a382059399e.png)

**Comment by koktaildotcom** [comment]
I added a bugfix for this.
