### ISSUE TITLE
Keep communication local (optionally)

### ISSUE THREAD

**Issue by pro-sumer** [koktaildotcom/com.p1.smartmeter-dsmr.reader#3]
This script posts data to `https://<homeyid>.connect.athom.com/api/app/com.p1/update`, which requires a DNS lookup. Apparently this DNS entry has a time-to-live of only 60 seconds. I'm experimenting with [NextDNS](https://nextdns.io), which is free while in beta, but will [cost](https://nextdns.io/pricing) $1,99/month if you make more than about 300,000 DNS queries/month. This script alone will exceed that limit...

On the other hand, my Homey has a fixed IP address in my network. Therefore, I would like to use that IP address instead of the domain name (i.e., `http://<ip-address>/api/app/com.p1/update`). That would prevent the DNS lookups and would also mean that the script would still work if there's an internet outage.

Unfortunately just changing the URL does not seem to work.

What else would be needed to get this to work? (If possible at all?)

**Comment by lucasvdh** [comment]
If you're already running this reader that means you've probably got a raspberry pi or some other Linux device at your disposal. My suggestion would be to get a yourself a [pi-hole](https://pi-hole.net/) :smiley: that caches DNS queries for you, improves overall network speed and it also blocks adds :+1:

Regarding the actual issue; accessing the api of the homey app via the local IP should work, shouldn't it? I know I've debugged this before using the local IP address.. I'll try and see if I can get it to work on my Homey.

**Comment by pro-sumer** [comment]
I use [Diversion](https://diversion.ch) on top of the custom [Asuswrt-Merlin](https://www.asuswrt-merlin.net) firmware on an ASUS router to block adds, but I'm also experimenting with [NextDNS](https://nextdns.io). So I do have options to redirect the request (either in NextDNS, or in [dnsmasq](https://en.wikipedia.org/wiki/Dnsmasq) on the router).

Yesterday I just used a hardcoded IP in the script. For a moment I saw updates appearing in the Homey App, but then it suddenly stopped. I thought the few updates were from what remained in the queue while using the Athom address, but I'll probably need to do some more testing.

(if my hunch is correct redirecting the address won't help)

**Comment by lucasvdh** [comment]
I can access the `com.p1` app just fine via the local IP of my Homey, my guess is that the issue is with either your network configuration or something goes wrong in the reader script. I haven't had the time to actually test the reader script posting to a local address.

**Comment by pro-sumer** [comment]
> I can access the com.p1 app just fine via the local IP of my Homey

What kind of access? `GET` or `PUT`?

Which endpoint? `/api/app/com.p1/update`?

**Comment by lucasvdh** [comment]
Yes, that endpoint and a `PUT`.

**Comment by pro-sumer** [comment]
When using the correct IP address I can as well...

**Comment by koktaildotcom** [comment]
Nice! I'll add that in the documentation
