### ISSUE TITLE
Question: use ip instead of usb

### ISSUE THREAD

**Issue by zuidwijk** [koktaildotcom/com.p1.smartmeter-dsmr.reader#7]
Hi, i see the configuration for an usb device:
```
const usbPort = '/dev/ttyUSB0'
const bps = 115200
const bits = 8;
const parity = 'none';
```

Is there a way to use an network address, like a telnet session?

I've got a device which reads the telegrams from the P1 port and spits them out via telnet (like esp-link). 

The output is exact the same as that from an usb device.

**Comment by koktaildotcom** [comment]
The package supports only USB unfortunately
